### ISSUE TITLE
Update to newest Raspbian Jessie Stretch

### ISSUE THREAD

**Issue by DavidGla** [viktorgino/headunit-desktop#28]
Hey,
first of all I want to say that you did an awsome work!
But there are three things I can´t get through.
1. In the settings I can adjust a directory for my music but the player itself does not recognize any song/directory
2. If I want to connect my Phone via USB, to start android auto, I first have to restart the service in the settings. Is there any other way?
3. Do you plan to switch to Raspbian Jessie Stretch? Not the Lite version? Because I found out, that in the newest Raspbian version the a2dp sink is working not only for telephone. 

I hope that the my contribution is not to rude. 
Greetings David

**Comment by viktorgino** [comment]
Hi

1. The music player is still a little buggy, but I'm planning some work on it, so this issue should be fixed soon.

2. I have a fix for this already, will be part of the latest image, which im hoping to get online tonight

3. Lite or not shouldn't make a difference for A2DP, the only difference is that there is a desktop environment installed on top of the lite system + some desktop apps. A2DP doesn't properly work on stock Raspbian, because it has a dated version of pulseaudio, which I've updated in my image.

**Comment by DavidGla** [comment]
Hi,

this sounds pretty good. Thanks for that!
Accordings to the A2DP, I found this tutorial which works perfect.
https://scribles.net/enabling-hands-free-profile-on-raspberry-pi-raspbian-stretch-by-using-pulseaudio/
